exponential_rate: 2.0
glass_item:
  material: "BLACK_STAINED_GLASS_PANE"
  name: "&6Price: %price%"
  lore: ["&7Unlock Slot #%slot%"]
  model_data: 1234
shulker_item:
  unlocked:
    material: "LIME_SHULKER_BOX"
    name: "&aVault #%vault%"
    model_data: 5678
  locked:
    material: "GRAY_SHULKER_BOX"
    name: "&7Vault #%vault%"
    model_data: 5678
messages:
  vault_not_unlocked: "&cYou need to unlock the previous vault to access this one!"
  slot_not_unlocked: "&cYou need to unlock the previous slot first!"
  not_enough_money: "&cNot enough money to unlock this slot!"
  slot_unlocked: "&aSlot unlocked!"
  vault_unlocked: "&aVault #%vault% unlocked!"
  player_not_found: "&cPlayer not found."
  only_players: "&cOnly players can use this command."
  no_permission: "&cYou do not have permission to use this command."
  invalid_action: "&cInvalid action. Use 'open' or 'view'."
commands:
  pv:
    description: "&7Open your vault or a specific vault"
    usage: "/pv [number]"
  pvadmin:
    description: "&7Admin commands for managing player vaults"
    usage: "/pvadmin <open/view> <player> [number]"
    permission: "sakuravaults.admin"
gui:
  vault_name: "&6CustomVault: &e#%vault%"
